# Generated by Django 3.2.2 on 2021-05-09 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'item_category',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('item_type_tag', models.CharField(choices=[('M', 'MEDICATION'), ('S', 'SUPPLY')], max_length=100)),
            ],
            options={
                'db_table': 'item_type',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('size', models.CharField(max_length=40)),
                ('asset_id', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtype')),
            ],
            options={
                'verbose_name': 'Item Parent',
                'db_table': 'item_parent',
                'abstract': False,
            },
        ),
    ]
