# Generated by Django 3.2.2 on 2021-05-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Item Parent Model',
                'db_table': 'item_parent',
            },
        ),
    ]
