# Generated by Django 3.2.2 on 2021-05-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelTable(
            name='asset',
            table='item_asset',
        ),
    ]
