# Generated by Django 3.2.2 on 2021-05-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210509_0401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='ItemAsset',
        ),
        migrations.CreateModel(
            name='ItemMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('size', models.CharField(max_length=40)),
                ('brand_name', models.CharField(max_length=120)),
                ('concentration', models.CharField(max_length=40)),
                ('is_controlled', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtype')),
            ],
            options={
                'db_table': 'item_medication',
            },
        ),
    ]
