# Generated by Django 3.2.2 on 2021-05-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210509_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='item_type_tag',
        ),
    ]
