# Generated by Django 3.2.2 on 2021-05-10 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210509_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemasset',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory'),
        ),
        migrations.AlterField(
            model_name='itemmedication',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory'),
        ),
    ]
